### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 6507: invalid start byte

### ISSUE THREAD

**Issue by akarsh42** [andrejonasson/question_answering#2]
while running the 
python question_answering/preprocessing/squad_preprocess.py

getting below error  (running on windows)

Downloading datasets into download\squad
Preprocessing datasets into data\squad
File train-v1.1.json successfully loaded
Preprocessing train: 100%|███████████████████████████████████████████████████████████| 442/442 [00:38<00:00, 11.40it/s]
Skipped 5852 question/answer pairs in train
Splitting the dataset into train and validation
Shuffling...
Traceback (most recent call last):
  File "question_answering/preprocessing/squad_preprocess.py", line 230, in <module>
    split_tier(data_prefix, 0.95, shuffle=True)
  File "question_answering/preprocessing/squad_preprocess.py", line 195, in split_tier
    save_files(prefix, 'val', indices_dev)
  File "question_answering/preprocessing/squad_preprocess.py", line 178, in save_files
    context_file.write(linecache.getline(os.path.join(prefix, 'train.context'), i).decode('utf8', 'ignore'))
  File "C:\ProgramData\Anaconda3\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "C:\ProgramData\Anaconda3\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\ProgramData\Anaconda3\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "C:\ProgramData\Anaconda3\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 6507: invalid start byte

**Comment by andrejonasson** [comment]
This is part of CS224n's input processing. I got the same error when I tried to run the script on Windows. I have not had the time to look into this particular error.

If you have access to a Linux installation it should work and the data files generated in Linux should also be usable in Windows.

**Comment by akarsh42** [comment]
generated data files in Linux 

on trying "python main.py"
I am getting the below error

Traceback (most recent call last):
  File "main.py", line 432, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 406, in main
    embeddings = np.load(embed_path)['glove']  # 115373
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 370, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '..\\data\\squad\\glove.trimmed.100.npz'

**Comment by akarsh42** [comment]
i changed the "tf.app.flags.DEFINE_integer("embedding_size", 300, "Size of the pretrained vocabulary.")"
embedding_size to 300
which is giving me the below error

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
INFO:root:Number of parameters 1465408
INFO:root:Variable <tf.Variable 'prediction/initial_encoder/bidirectional_rnn/fw/lstm_cell/kernel:0' shape=(400, 400) dtype=float32_ref> has 160000 entries
INFO:root:Variable <tf.Variable 'prediction/initial_encoder/bidirectional_rnn/fw/lstm_cell/bias:0' shape=(400,) dtype=float32_ref> has 400 entries
INFO:root:Variable <tf.Variable 'prediction/initial_encoder/dense/kernel:0' shape=(200, 200) dtype=float32_ref> has 40000 entries
INFO:root:Variable <tf.Variable 'prediction/initial_encoder/dense/bias:0' shape=(200,) dtype=float32_ref> has 200 entries
INFO:root:Variable <tf.Variable 'prediction/coattention_1/document_sentinel:0' shape=(200,) dtype=float32_ref> has 200 entries
INFO:root:Variable <tf.Variable 'prediction/coattention_1/query_sentinel:0' shape=(200,) dtype=float32_ref> has 200 entries
INFO:root:Variable <tf.Variable 'prediction/summary_encoder/bidirectional_rnn/fw/lstm_cell/kernel:0' shape=(300, 400) dtype=float32_ref> has 120000 entries
INFO:root:Variable <tf.Variable 'prediction/summary_encoder/bidirectional_rnn/fw/lstm_cell/bias:0' shape=(400,) dtype=float32_ref> has 400 entries
INFO:root:Variable <tf.Variable 'prediction/final_encoder/bidirectional_rnn/fw/lstm_cell/kernel:0' shape=(1300, 400) dtype=float32_ref> has 520000 entries
INFO:root:Variable <tf.Variable 'prediction/final_encoder/bidirectional_rnn/fw/lstm_cell/bias:0' shape=(400,) dtype=float32_ref> has 400 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/lstm_cell/kernel:0' shape=(500, 400) dtype=float32_ref> has 200000 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/lstm_cell/bias:0' shape=(400,) dtype=float32_ref> has 400 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/start/dense/kernel:0' shape=(500, 100) dtype=float32_ref> has 50000 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/start/dense_1/kernel:0' shape=(300, 400) dtype=float32_ref> has 120000 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/start/dense_1/bias:0' shape=(400,) dtype=float32_ref> has 400 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/start/dense_2/kernel:0' shape=(100, 400) dtype=float32_ref> has 40000 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/start/dense_2/bias:0' shape=(400,) dtype=float32_ref> has 400 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/start/dense_3/kernel:0' shape=(200, 4) dtype=float32_ref> has 800 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/start/dense_3/bias:0' shape=(4,) dtype=float32_ref> has 4 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/end/dense/kernel:0' shape=(500, 100) dtype=float32_ref> has 50000 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/end/dense_1/kernel:0' shape=(300, 400) dtype=float32_ref> has 120000 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/end/dense_1/bias:0' shape=(400,) dtype=float32_ref> has 400 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/end/dense_2/kernel:0' shape=(100, 400) dtype=float32_ref> has 40000 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/end/dense_2/bias:0' shape=(400,) dtype=float32_ref> has 400 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/end/dense_3/kernel:0' shape=(200, 4) dtype=float32_ref> has 800 entries
INFO:root:Variable <tf.Variable 'prediction/decoder_loop/end/dense_3/bias:0' shape=(4,) dtype=float32_ref> has 4 entries
2018-01-27 07:41:43.944301: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-01-27 07:41:55.214195: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: flat indices[21, :] = [21, 400] does not index into param (shape: [32,400,200]).
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[21, :] = [21, 400] does not index into param (shape: [32,400,200]).
         [[Node: prediction_1/decoder_loop/GatherNd_1 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prediction/dropout/mul, prediction_1/decoder_loop/stack_2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 432, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 420, in main
    do_train(model, train, dev)
  File "main.py", line 278, in do_train
    result = sess.run(fetch_dict, feed_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[21, :] = [21, 400] does not index into param (shape: [32,400,200]).
         [[Node: prediction_1/decoder_loop/GatherNd_1 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prediction/dropout/mul, prediction_1/decoder_loop/stack_2)]]

Caused by op 'prediction_1/decoder_loop/GatherNd_1', defined at:
  File "main.py", line 432, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 410, in main
    model = DCN(embeddings, FLAGS.__flags)
  File "E:\DCN\question_answering\networks\dcn_model.py", line 82, in __init__
    logits = dcn_decode(encoding, self.paragraph_length, hparams['state_size'], hparams['pool_size'], hparams['max_iter'], keep_prob=maybe_dropout(hparams['keep_prob'], self.is_training))
  File "E:\DCN\question_answering\networks\dcn_plus.py", line 400, in dcn_decode
    output, state = lstm_dec(start_and_end_encoding(encoding, answer), state)
  File "E:\DCN\question_answering\networks\dcn_plus.py", line 351, in start_and_end_encoding
    encoding_end = tf.gather_nd(encoding, tf.stack([tf.range(batch_size), end], axis=1))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1970, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): flat indices[21, :] = [21, 400] does not index into param (shape: [32,400,200]).
         [[Node: prediction_1/decoder_loop/GatherNd_1 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prediction/dropout/mul, prediction_1/decoder_loop/stack_2)]]

**Comment by akarsh42** [comment]
I also tried with tensorflow-gpu

it resulted in below error 



C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_flag.py", line 166, in _parse
    return self.parser.parse(argument)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_argument_parser.py", line 152, in parse
    val = self.convert(argument)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_argument_parser.py", line 268, in convert
    type(argument)))
TypeError: Expect argument to be a string or int, found <class 'bool'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 40, in <module>
    tf.app.flags.DEFINE_integer("trainable_initial_state", False, "Make RNNCell initial states trainable.")  # Not implemented
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_defines.py", line 315, in DEFINE_integer
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_flag.py", line 107, in __init__
    self._set_default(default)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_flag.py", line 196, in _set_default
    self.default = self._parse(value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --trainable_initial_state=False: Expect argument to be a string or int, found <class 'bool'>

**Comment by andrejonasson** [comment]
"InvalidArgumentError (see above for traceback): flat indices[21, :] = [21, 400] does not index into param (shape: [32,400,200])."

This should have been fixed in a previous update. The error only triggered during certain random seeds, so it was not caught when I first tried it after changing parts of the code. It is unrelated to embedding_size. 

If only embedding_size==300 works for you it's most likely because you generated embeddings of size 300 to begin with.

Try updating to fix it.

"TypeError: Expect argument to be a string or int, found <class 'bool'>"

Strange. I do not get this error. The code that should've been causing this is now fixed (please update) - the flag was incorrectly defined as integer rather than boolean. Maybe something has been updated and now it notices the difference between boolean (which is a subclass of int in Python) and int.

**Comment by akarsh42** [comment]
hi 
I pulled  the latest code 

but still no luck 

```
**DESKTOP-PIKNI27:/mnt/e/DCNPlus/dynamic-coattention-network-plus$ python question_answering/preprocessing/dwr.py --glove_source crawl_ci**

Storing datasets in download/dwr
Traceback (most recent call last):
  File "question_answering/preprocessing/dwr.py", line 29, in <module>
    glove_zip = maybe_download(glove_base_url, glove_filename, prefix, 862182613)
  File "/mnt/e/DCNPlus/dynamic-coattention-network-plus/question_answering/preprocessing/squad_preprocess.py", line 63, in maybe_download
    raise Exception("Unexpected dataset size. Please get the dataset using a browser.")
Exception: Unexpected dataset size. Please get the dataset using a browser.

```

> **I downloaded from the web and in zipped them to download**

then ran below commands
python preprocessing/qa_data.py --glove_dim 100 --glove_source wiki
python preprocessing/qa_data.py --glove_dim 200 --glove_source wiki
python preprocessing/qa_data.py --glove_dim 300 --glove_source wiki

**_```
python preprocessing/qa_data.py --glove_dim 300 --glove_source crawl_ci
python preprocessing/qa_data.py --glove_dim 300 --glove_source crawl_cs
the above two commands did nothing nor gave any error 
```_**

```
**so I ran 
python main.py
and got below error** 
```

E:\DCNPlus\dynamic-coattention-network-plus\question_answering>python main.py
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:root:Train/Dev size 81884/4326
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 141, in make_shape
    shape = tensor_shape.as_shape(v)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 849, in as_shape
    return TensorShape(shape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 455, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 455, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 397, in as_dimension
    return Dimension(value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 32, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Flag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 437, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "main.py", line 415, in main
    model = DCN(embeddings, FLAGS.__flags)
  File "E:\DCNPlus\dynamic-coattention-network-plus\question_answering\networks\dcn_model.py", line 40, in __init__
    self.question_chars = tf.placeholder(tf.int32, (None, None, self.hparams['max_word_length']), name='question_chars')
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4101, in _placeholder
    shape = _execute.make_shape(shape, "shape")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 143, in make_shape
    raise TypeError("Error converting %s to a TensorShape: %s." % (arg_name, e))
TypeError: Error converting shape to a TensorShape: int() argument must be a string, a bytes-like object or a number, not 'Flag'.

E:\DCNPlus\dynamic-coattention-network-plus\question_answering>python main.py

**Comment by andrejonasson** [comment]
`Exception: Unexpected dataset size. Please get the dataset using a browser.`

Should now be fixed, it was a bytes check that had not been removed from crawl download. Thanks for catching that.

"python preprocessing/qa_data.py --glove_dim 300 --glove_source crawl_ci
python preprocessing/qa_data.py --glove_dim 300 --glove_source crawl_cs"

This is because there is no feature to have two different glove sources at the same dimension. You've already created a 300 dimensional pretrained embeddings from wiki.

If you want to create 300 dim pretrained embeddings for crawl_ci for instance you will want to put the already created wiki one first into a temp folder then run the command.

`self.question_chars = tf.placeholder(tf.int32, (None, None, self.hparams['max_word_length']), name='question_chars')`

As written in the `main.py` hparams comments, the program does not support character embeddings yet. Set `use_char_cnn` to False until the feature is supported.
